### ISSUE TITLE
Return content

### ISSUE THREAD

**Issue by AustenLamacraft** [chriskirknielsen/eleventy-plugin-copy-local-assets#1]
I was playing around with Balazs' solution today and found I could only get it to work when I `return content` instead of just `return` when skipping copying. Not 100% sure, but it seems that 11ty expects a transform to return something.

**Comment by chriskirknielsen** [comment]
Hey, thanks for that info!

I am not sure if this plugin still works with Eleventy v1.0.0 due to how the content is passed in transforms, so I have kind of abandoned it, but if this is still useful to folks I'm happy to merge a PR if you want to send one. :)
